export const QUOTE_REQUEST_PENDING = 'QUOTE_REQUEST_PENDING';
export const QUOTE_REQUEST_SUCCESS = 'QUOTE_REQUEST_SUCCESS';
export const QUOTE_REQUEST_FAILED = 'QUOTE_REQUEST_FAILED';
export const GET_PREVIOUS_QUOTE = 'GET_PREVIOUS_QUOTE';
