export const colors = [
	"aliceblue", "azure", "aqua", "antiquewhite","aquamarine", "bisque", "blanchedalmond", "blueviolet", 
	"burlywood", "cadetblue","chartreuse", "coral", "cornflowerblue", "cornsilk", 
	"cyan", "darkslateblue", "darkslategray", "darkcyan", "darkgoldenrod", 
	"darkkhaki", "darkorange", "darkorchid", "darksalmon", 
	"darkseagreen", "darkturquoise", "deeppink", 
	"deepskyblue", "dodgerblue", "firebrick", "forestgreen","fuchsia", "gainsboro", 
	"gold", "goldenrod", "gray", "green", "greenyellow", "honeydew", "hotpink", "indianred", 
	"ivory", "khaki", "lavenderblush", "lawngreen","lemonchiffon", "lightblue", 
	"lightcoral", "lightcyan", "lightgoldenrodyellow", "lightgray","lightgreen", "lightpink", 
	"lightsalmon", "lightseagreen", "lightskyblue", "lightslategray", "lightsteelblue", "lime", 
	"limegreen", "linen", "magenta", "mediumorchid", "mediumaquamarine", 
	"mediumpurple", "mediumseagreen", "mediumspringgreen", "mediumturquoise", "mediumvioletred", 
	"mistyrose", "moccasin", "navajowhite", "olive", "olivedrab", "orchid","orange", "orangered",
	"palegoldenrod", "palegreen", "paleturquoise", "palevioletred", "papayawhip", "peachpuff", "peru",
	"pink", "plum", "powderblue", "rebeccapurple", "red", "rosybrown", "royalblue", 
	"saddlebrown", "salmon", "sandybrown", "seagreen", "sienna", "silver", "skyblue",
	"springgreen", "steelblue", "tan", "teal", "thistle", "tomato", "turquoise", "violet", "wheat",
	"yellow", "yellowgreen"
	];
